services:
  server:
    container_name: uniwork_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app               # Mount local code into container
      - /app/node_modules    # Keep container's node_modules separate
    ports:
      - "${SERVER_PORT}:8000"
    env_file:
      - .env
    depends_on:
       db:
        condition: service_healthy

  db:
    container_name: uniwork_db
    image: postgres:18
    restart: on-failure:3
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - uniwork_db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\"" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  uniwork_db_data:
